### ISSUE TITLE
[ compat ] build failure with latest Idris head

### ISSUE THREAD

**Issue by stefan-hoeck** [mattpolzin/idris-snocvect#2]
This failed to build when generating the latest pack nightly. I didn't look into the details yet. Just wanted to inform you.

**Comment by stefan-hoeck** [comment]
Damn those typos (in the title). I shouldn't open GitHub issues this early in the morning...

**Comment by mattpolzin** [comment]
Fixed by https://github.com/mattpolzin/idris-snocvect/pull/3
